# Generated by Django 3.2.18 on 2023-05-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20220829_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True},
        ),
    ]
