# Generated by Django 3.2.20 on 2023-07-11 14:25

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20220829_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='program',
            field=models.ManyToManyField(to='program.Program'),
        )
    ]
