# Generated by Django 3.2.20 on 2023-08-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_item_maximum_amount_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True},
        ),
    ]
