# Generated by Django 3.2.20 on 2023-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20220804_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='program',
            field=models.ManyToManyField(to='program.Program'),
        ),
    ]
