# Generated by Django 3.2.20 on 2023-08-16 16:00

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20230315_0851'),
        ('medical', '0008_auto_20230807_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='program',
        ),
        migrations.AddField(
            model_name='item',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_program', to='program.program'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='program',
        ),
        migrations.AddField(
            model_name='service',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_program', to='program.program'),
        ),
    ]
