# Generated by Django 3.2.20 on 2024-07-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20230816_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(db_column='ServCode', max_length=20),
        )
    ]
