# Generated by Django 3.2.17 on 2023-05-12 11:38

import core.fields
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20230512_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemcategory',
            field=models.CharField(blank=True, db_column='ItemCategory', max_length=100, null=True),
        )
    ]
