# Generated by Django 3.2.17 on 2023-06-12 11:24

import core.fields
import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='id',
            field=models.AutoField(db_column='idPCP', primary_key=True, serialize=False),
        ),
    ]
