# Generated by Django 4.2.17 on 2024-12-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_item_maximum_amount_alter_item_quantity_and_more'),
        ('medical', '0009_alter_service_patient_category'),
    #    ('medical', '0009_merge_20230714_0836'),
        ('medical', '0010_auto_20240710_1057'),
    ]

    operations = [
    ]