# Generated by Django 3.2.25 on 2024-08-12 11:13

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20230816_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='health_facility',
            field=models.ForeignKey(db_column='health_facility', null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthFacilityItems', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='service',
            name='health_facility',
            field=models.ForeignKey(db_column='health_facility', null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthFacilityServices', to='location.healthfacility'),
        ),
    ]
