# Generated by Django 4.2.20 on 2025-03-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20220829_2102'),
        ('medical', '0008_auto_20220804_1112'),
        ('medical', '0011_auto_20240812_1113'),
        ('medical', '0011_merge_20241211_1731'),
    ]

    operations = [
    ]
